FROM almalinux:9
RUN dnf install nginx -y
LABEL project="expense" \
      owner="Chouda Reddy" \
      environment="production" \
      version="1.0" \
      description="This is a simple expense management application" \
      component="frontend"