FROM almalinux:9
RUN dnf install nginx -y
RUN rm -rf /usr/share/nginx/html/index.html
ADD https://github.com/DevSecOpsWithAWS/Shell-Script/blob/main/04.Variables.sh /usr/share/nginx/html/index.html
RUN chmod +r /usr/share/nginx/html/index.html
#ADD sample-1.tar
CMD ["nginx","-g","daemon off;"]